### ISSUE TITLE
Semantic Mispelling

### ISSUE THREAD

**Issue by lnhrdt** [denisa/clq#443]
Hey @denisa! I just discovered your clq tool and GitHub Actions today. I'm really impressed and excited to start using these tools in a few of my projects.

I noticed a small typo in your changelog badges: `Sematic Versioning` should be `Semantic Versioning`.

It looks like this typo has been copied over to a few repos:
https://github.com/search?q=%22img.shields.io%2Fbadge%2FSematic%2520Versioning%22&type=code

I almost copied it into my own project, so I thought I'd mention it here, even though it's a minor issue!

**Comment by denisa** [comment]
That's embarrassing 😊 

Many thanks!
